version: '3.4'

services:

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: synel-backend-container
    image: synel-backend-image:latest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database
    ports:
      - 8080:80
      - 4343:443
    networks:
      - db_bridge

  database:
    build: 
      context: .
      dockerfile: ./apps/postgres/Dockerfile
    container_name: synel-database-container
    hostname: synel-database-host
    image: synel-database-image
    restart: always
    ports:
      - 5432:5432
    networks:
      - db_bridge
    
networks:
  db_bridge:
    driver: bridge